# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-01 09:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('english_content', models.TextField()),
                ('polish_content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50)),
                ('author', models.CharField(max_length=50)),
                ('date', models.DateTimeField()),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Content')),
            ],
        ),
    ]
