# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-01 09:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='english_title',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='content',
            name='polish_title',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
