# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-02 09:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20170401_0942'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='english_link',
            field=models.CharField(default=None, max_length=60, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='content',
            name='polish_link',
            field=models.CharField(default=None, max_length=60, unique=True),
            preserve_default=False,
        ),
    ]
